### ISSUE TITLE
A/B Test preview does not show variant title

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/experiments#53]
Steps to reproduce:

On local server
1. Create a new post
2. Click on the A/B tab
3. Add a variant title
4. Update the post
5. Start the test
6. Click the Preview link for the variant title
7. Original title is displayed

![2021-01-11 at 3 31 PM](https://user-images.githubusercontent.com/991511/104245809-2c130f80-5422-11eb-80fb-e37898208c39.gif)

https://github.com/humanmade/product-dev/issues/602

**Comment by roborourke** [comment]
Must be some issue with setting the local storage value. Are there any errors in the JS console?

**Comment by jazzsequence** [comment]
Nope, no console errors.

**Comment by jazzsequence** [comment]
This appears to have been an issue with my local install and was resolved after destroying and recreating the docker containers.

**Comment by roborourke** [comment]
Interesting. I was wondering if you had rejected all cookie categories or something like that. Glad that’s one less thing to fix :)
